name: Trivy Scan

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '29 12 * * 0'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: "ubuntu-18.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'python:3.6-slim-buster'
          format: 'json'
          output: 'trivy-slim-buster.json'

      - name: 'Safe trivy-indy-node-latest.sarif'
        uses: actions/upload-artifact@v2
        with:
          name: trivy-slim-buster.json
          path: trivy-slim-buster.json
          retention-days: 8
      
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-slim-buster.sarif'
